# Generated by Django 5.0.1 on 2024-07-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_container_expensetype_productsize_worker_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='come_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='container',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
