# Generated by Django 5.0.1 on 2024-07-14 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_container_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_container',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.container', verbose_name='cointainer nomi'),
            preserve_default=False,
        ),
    ]
