# Generated by Django 5.0.1 on 2024-07-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_paid_summa_alter_orderitem_product_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid_summa',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_summa',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='container',
            name='paid_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Container balansi'),
        ),
    ]
