# Generated by Django 5.0.1 on 2024-07-22 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_order_paid_summa_remove_order_total_summa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.base')),
                ('currency', models.IntegerField(choices=[(1, 'USD'), (2, 'UZS')], default=2)),
                ('sale_exchange_rate', models.IntegerField(verbose_name='Valyuta kursi')),
                ('payment_amount', models.FloatField(verbose_name="To'langan summa")),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.client')),
            ],
            bases=('main.base',),
        ),
    ]
