# Generated by Django 5.0.1 on 2024-07-23 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_payment_container_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='container_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.container'),
        ),
    ]
