# Generated by Django 5.0.1 on 2024-07-23 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_container_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='debt_usd',
        ),
        migrations.RemoveField(
            model_name='client',
            name='debt_uzs',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='container_payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.base')),
                ('debt_usd', models.IntegerField(default=0, verbose_name='Qarz USD')),
                ('debt_uzs', models.IntegerField(default=0, verbose_name='Qarz UZS')),
                ('client_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_account', to='main.client')),
                ('container_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.container')),
            ],
            bases=('main.base',),
        ),
        migrations.AddField(
            model_name='payment',
            name='client_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.clientaccount'),
        ),
    ]
