# Generated by Django 5.0.1 on 2024-07-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_client_debt_usd_remove_client_debt_uzs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qaytarilgan tovar miqdori'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.FloatField(default=0, verbose_name="To'langan summa"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale_exchange_rate',
            field=models.IntegerField(default=0, verbose_name='Valyuta kursi'),
        ),
    ]
