# Generated by Django 5.0.1 on 2024-07-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_productsize_status_alter_orderitem_return_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_cut',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
