# Generated by Django 5.0.1 on 2024-07-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_product_product_cube_alter_product_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='come_cost',
            field=models.IntegerField(default=0, verbose_name='Kelgan narxi'),
        ),
    ]
