# Generated by Django 5.0.1 on 2024-07-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_product_come_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rest_cube',
            field=models.FloatField(default=0, verbose_name='Qoldiq miqdori / metr kub'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rest_qty',
            field=models.IntegerField(default=0, verbose_name='Qoldiq soni / dona'),
        ),
    ]
