# Generated by Django 5.0.1 on 2024-07-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_expense_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount_sold',
            field=models.FloatField(verbose_name='Sotilgan miqdori | dona'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_cost',
            field=models.FloatField(verbose_name='Mahsulot narxi'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='return_qty',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Qaytarilgan tovar miqdori'),
        ),
    ]
