# Generated by Django 5.0.1 on 2024-07-31 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_clientaccount_debt_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.base')),
                ('title', models.CharField(max_length=255, verbose_name='Zametka nomi')),
                ('text', models.TextField()),
                ('date_of_notice', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=('main.base',),
        ),
    ]
