# Generated by Django 5.0.1 on 2024-08-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
