# Generated by Django 5.0.1 on 2024-08-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_container_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='product_size_title',
            field=models.CharField(default='text', max_length=255, verbose_name='Nomi'),
        ),
    ]
