# Generated by Django 5.0.1 on 2024-09-17 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_order_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.base')),
                ('name', models.CharField(max_length=255, verbose_name="Ta'minotchining ismi")),
                ('phone', models.CharField(max_length=13, verbose_name='telefon raqami')),
                ('usd_summa', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=('main.base',),
        ),
        migrations.AddField(
            model_name='container',
            name='debt_summa',
            field=models.FloatField(default=0, verbose_name="Ta'minotchidan qarz"),
        ),
        migrations.AddField(
            model_name='container',
            name='paid_summa',
            field=models.FloatField(default=0, verbose_name="Ta'minotchiga to'langan summa"),
        ),
        migrations.CreateModel(
            name='PaymentToSupplier',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.base')),
                ('paid_summa', models.FloatField(default=0)),
                ('debt', models.FloatField(default=0)),
                ('container_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.container')),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supplier')),
            ],
            bases=('main.base',),
        ),
        migrations.AddField(
            model_name='container',
            name='supplier_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.supplier'),
        ),
    ]
