# Generated by Django 4.2.14 on 2024-10-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_supplier_container_debt_summa_container_paid_summa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='supplier_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='main.supplier'),
        ),
        migrations.AlterField(
            model_name='paymenttosupplier',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_supplier', to='main.supplier'),
        ),
    ]
