# Generated by Django 4.2.14 on 2024-10-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_container_supplier_container_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='container_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='main.container'),
        ),
    ]
